# CitySmart Parking App - Analysis Options
# Enhanced with custom rules to prevent common deployment issues

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
  
  errors:
    # Treat these as errors to prevent deployment issues
    use_build_context_synchronously: warning
    invalid_annotation_target: error
    missing_required_param: error

linter:
  rules:
    # Core rules for code quality
    avoid_print: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    
    # Navigation and routing rules
    use_build_context_synchronously: true
    
    # Performance rules
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_decorated_box: true
    
    # Style consistency
    constant_identifier_names: true
    file_names: true
    non_constant_identifier_names: true
    
    # Error prevention
    avoid_returning_null_for_void: true
    cancel_subscriptions: true
    close_sinks: true
    
    # Widget best practices
    use_key_in_widget_constructors: true
    prefer_const_constructors_in_immutables: true
    avoid_web_libraries_in_flutter: true
    
    # Accessibility
    use_colored_box: true
    
    # Code organization
    directives_ordering: true
    sort_child_properties_last: true
    
    # Type safety (warnings for now)
    avoid_dynamic_calls: false
    avoid_type_to_string: false
