workflows:
  web-release:
    name: Build Web App
    environment:
      flutter: stable
      vars:
        BUILD_DIR: build/web
    cache:
      cache_paths:
        - ~/.pub-cache
    scripts:
      - name: Clean build directories
        script: flutter clean
      - name: Get dependencies
        script: flutter pub get
      - name: Build web release
        script: flutter build web --release
    artifacts:
      - $BUILD_DIR/**
    publishing:
      email:
        recipients:
          - mkeparkapp@gmail.com
  ios-testflight:
    name: Publish iOS to TestFlight
    environment:
      flutter: stable
      xcode: latest
      groups:
        - app_store_connect_credentials
      vars:
        PACKAGE_NAME: "com.mkeparkapp.app"
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/Library/Caches/CocoaPods
    scripts:
      - name: Clean build directories
        script: flutter clean
      - name: Get dependencies
        script: flutter pub get
      - name: Set up automatic signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files \
            --type IOS_APP_DEVELOPMENT \
            --bundle-identifier com.mkeparkapp.app \
            --team-id J8U8FW3PA8 \
            --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build IPA
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        submit_to_app_store: false
        submit_to_testflight: true
      email:
        recipients:
          - mkeparkapp@gmail.com
