workflows:
  android-google-play:
    name: Publish Android to Google Play
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Clean build directories
        script: |
          flutter clean
          rm -rf ~/.gradle/caches/*/fileHashes
      - name: Get dependencies
        script: flutter pub get
      - name: Build app bundle
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT
        track: internal
      email:
        recipients:
          - mkeparkapp@gmail.com
  ios-testflight:
    name: Publish iOS to TestFlight
    environment:
      flutter: stable
      xcode: latest
      vars:
        PACKAGE_NAME: "com.mkeparkapp.app"
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/Library/Caches/CocoaPods
    scripts:
      - name: Clean build directories
        script: flutter clean
      - name: Get dependencies
        script: flutter pub get
      - name: Set up automatic signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files \
            --type IOS_APP_DEVELOPMENT \
            --bundle-ids com.mkeparkapp.app \
            --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build IPA
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_app_store: false
        submit_to_testflight: true
      email:
        recipients:
          - mkeparkapp@gmail.com
