workflows:
  web-release:
    name: Build Web App
    environment:
      flutter: stable
      vars:
        BUILD_DIR: build/web
    cache:
      cache_paths:
        - ~/.pub-cache
    scripts:
      - name: Clean build directories
        script: flutter clean
      - name: Get dependencies
        script: flutter pub get
      - name: Build web release
        script: flutter build web --release
    artifacts:
      - $BUILD_DIR/**
    publishing:
      email:
        recipients:
          - mkeparkapp@gmail.com
  ios-testflight:
    name: Publish iOS to TestFlight
    environment:
      flutter: stable
      xcode: latest
      groups:
        - app_store_connect_credentials
      vars:
        PACKAGE_NAME: "com.mkeparkapp.app"
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/Library/Caches/CocoaPods
    scripts:
      - name: Clean build directories
        script: flutter clean
      - name: Get dependencies
        script: flutter pub get
      - name: Set up automatic signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files \
            --type IOS_APP_DEVELOPMENT \
            --bundle-id com.mkeparkapp.app \
            --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build IPA
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR1RBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJIa3dkd0lCQVFRZ1plZXRxZjNZcXdUKzZ5eUsKbngwVjN0U05OalZPNXpRU2dnbC8zcEN4c0pxZ0NnWUlLb1pJemowREFRZWhSQU5DQUFTQ1Fucy91QWNVR0R5Ugp1QkhUTXIvUWIrL0lhcHV1c01lYmlnNkdEUWtzQWxHMHdFa1dyYkZPNXFLMkFMaEdMMmszcDN3U1duTGhUYlFnCmZPdGVpWjgyCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=
        key_id: 24FX2U2QTR
        issuer_id: 89dbf878-5b33-447c-a23c-3bac56284750
        submit_to_app_store: false
        submit_to_testflight: true
      email:
        recipients:
          - mkeparkapp@gmail.com
