// Mocks generated by Mockito 5.4.6 from annotations
// in mkecitysmart/test/unit/risk_alert_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:ui' as _i25;

import 'package:geolocator/geolocator.dart' as _i14;
import 'package:mkecitysmart/models/ad_preferences.dart' as _i3;
import 'package:mkecitysmart/models/city_rule_pack.dart' as _i5;
import 'package:mkecitysmart/models/garbage_schedule.dart' as _i22;
import 'package:mkecitysmart/models/maintenance_report.dart' as _i9;
import 'package:mkecitysmart/models/night_parking_permission.dart' as _i24;
import 'package:mkecitysmart/models/parking_zone.dart' as _i15;
import 'package:mkecitysmart/models/payment_receipt.dart' as _i8;
import 'package:mkecitysmart/models/permit.dart' as _i18;
import 'package:mkecitysmart/models/permit_eligibility.dart' as _i7;
import 'package:mkecitysmart/models/reservation.dart' as _i19;
import 'package:mkecitysmart/models/sighting_report.dart' as _i21;
import 'package:mkecitysmart/models/street_sweeping.dart' as _i10;
import 'package:mkecitysmart/models/subscription_plan.dart' as _i4;
import 'package:mkecitysmart/models/ticket.dart' as _i20;
import 'package:mkecitysmart/models/vehicle.dart' as _i23;
import 'package:mkecitysmart/providers/user_provider.dart' as _i6;
import 'package:mkecitysmart/services/city_ticket_stats_service.dart' as _i2;
import 'package:mkecitysmart/services/location_service.dart' as _i13;
import 'package:mkecitysmart/services/notification_service.dart' as _i11;
import 'package:mkecitysmart/services/ticket_risk_prediction_service.dart'
    as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCityTicketStats_0 extends _i1.SmartFake
    implements _i2.CityTicketStats {
  _FakeCityTicketStats_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdPreferences_1 extends _i1.SmartFake implements _i3.AdPreferences {
  _FakeAdPreferences_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSubscriptionPlan_2 extends _i1.SmartFake
    implements _i4.SubscriptionPlan {
  _FakeSubscriptionPlan_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCityRulePack_3 extends _i1.SmartFake implements _i5.CityRulePack {
  _FakeCityRulePack_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePhoneAuthStartResult_4 extends _i1.SmartFake
    implements _i6.PhoneAuthStartResult {
  _FakePhoneAuthStartResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePermitEligibilityResult_5 extends _i1.SmartFake
    implements _i7.PermitEligibilityResult {
  _FakePermitEligibilityResult_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaymentReceipt_6 extends _i1.SmartFake
    implements _i8.PaymentReceipt {
  _FakePaymentReceipt_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMaintenanceReport_7 extends _i1.SmartFake
    implements _i9.MaintenanceReport {
  _FakeMaintenanceReport_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreetSweepingSchedule_8 extends _i1.SmartFake
    implements _i10.StreetSweepingSchedule {
  _FakeStreetSweepingSchedule_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i11.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<void> initialize({required bool? enableRemoteNotifications}) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {
              #enableRemoteNotifications: enableRemoteNotifications,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> showLocal({
    required String? title,
    required String? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showLocal, [], {#title: title, #body: body}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> scheduleLocal({
    required String? title,
    required String? body,
    required DateTime? when,
    int? id,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleLocal, [], {
              #title: title,
              #body: body,
              #when: when,
              #id: id,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> scheduleRepeatingReminders({
    required String? title,
    required String? body,
    required DateTime? startTime,
    required DateTime? cutoffTime,
    required int? baseId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleRepeatingReminders, [], {
              #title: title,
              #body: body,
              #startTime: startTime,
              #cutoffTime: cutoffTime,
              #baseId: baseId,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> cancelAllScheduled() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllScheduled, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> cancelScheduled(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#cancelScheduled, [id]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> syncAspNotifications({
    required bool? morningEnabled,
    required bool? eveningEnabled,
    required bool? midnightEnabled,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncAspNotifications, [], {
              #morningEnabled: morningEnabled,
              #eveningEnabled: eveningEnabled,
              #midnightEnabled: midnightEnabled,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> syncSweepingNotifications({
    required List<
      ({
        bool advance24h,
        bool final2h,
        String id,
        DateTime nextSweep,
        String zone,
      })
    >?
    schedules,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncSweepingNotifications, [], {
              #schedules: schedules,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> cancelSweepingNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#cancelSweepingNotifications, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> scheduleNightParkingEveningReminder({
    required bool? hasPermit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleNightParkingEveningReminder, [], {
              #hasPermit: hasPermit,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> scheduleNightParkingExpirationReminder({
    required DateTime? expirationDate,
    int? daysBeforeExpiry = 30,
    int? idOffset = 2,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleNightParkingExpirationReminder, [], {
              #expirationDate: expirationDate,
              #daysBeforeExpiry: daysBeforeExpiry,
              #idOffset: idOffset,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> scheduleNightParkingTimeReminder({
    required DateTime? when,
    required int? idOffset,
    required String? title,
    required String? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleNightParkingTimeReminder, [], {
              #when: when,
              #idOffset: idOffset,
              #title: title,
              #body: body,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> cancelNightParkingReminders() =>
      (super.noSuchMethod(
            Invocation.method(#cancelNightParkingReminders, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void setAlertLimitCallback(_i12.Future<bool> Function()? callback) =>
      super.noSuchMethod(
        Invocation.method(#setAlertLimitCallback, [callback]),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> reregisterTokenAfterSignIn() =>
      (super.noSuchMethod(
            Invocation.method(#reregisterTokenAfterSignIn, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i13.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i14.Position?> getCurrentPosition() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPosition, []),
            returnValue: _i12.Future<_i14.Position?>.value(),
          )
          as _i12.Future<_i14.Position?>);

  @override
  double calculateDistanceKm({
    required double? startLat,
    required double? startLng,
    required double? endLat,
    required double? endLng,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#calculateDistanceKm, [], {
              #startLat: startLat,
              #startLng: startLng,
              #endLat: endLat,
              #endLng: endLng,
            }),
            returnValue: 0.0,
          )
          as double);

  @override
  List<_i15.ParkingZone> loadDefaultZones() =>
      (super.noSuchMethod(
            Invocation.method(#loadDefaultZones, []),
            returnValue: <_i15.ParkingZone>[],
          )
          as List<_i15.ParkingZone>);

  @override
  List<String> searchAddresses(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchAddresses, [query]),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> buildWalkingDirections({
    required _i14.Position? start,
    required _i15.ParkingZone? destination,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#buildWalkingDirections, [], {
              #start: start,
              #destination: destination,
            }),
            returnValue: <String>[],
          )
          as List<String>);
}

/// A class which mocks [TicketRiskPredictionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTicketRiskPredictionService extends _i1.Mock
    implements _i16.TicketRiskPredictionService {
  MockTicketRiskPredictionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double predictRisk({
    required DateTime? when,
    required double? latitude,
    required double? longitude,
    double? eventLoad = 0.0,
    double? historicalDensity = 0.0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#predictRisk, [], {
              #when: when,
              #latitude: latitude,
              #longitude: longitude,
              #eventLoad: eventLoad,
              #historicalDensity: historicalDensity,
            }),
            returnValue: 0.0,
          )
          as double);

  @override
  double predictRiskWithCityStats({
    required DateTime? when,
    required double? latitude,
    required double? longitude,
    double? eventLoad = 0.0,
    double? historicalDensity = 0.0,
    double? monthlyFactor = 0.0,
    double? cityHotspotDensity = 0.0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#predictRiskWithCityStats, [], {
              #when: when,
              #latitude: latitude,
              #longitude: longitude,
              #eventLoad: eventLoad,
              #historicalDensity: historicalDensity,
              #monthlyFactor: monthlyFactor,
              #cityHotspotDensity: cityHotspotDensity,
            }),
            returnValue: 0.0,
          )
          as double);

  @override
  String riskMessage(double? score) =>
      (super.noSuchMethod(
            Invocation.method(#riskMessage, [score]),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.method(#riskMessage, [score]),
            ),
          )
          as String);

  @override
  String getEnforcementSummary() =>
      (super.noSuchMethod(
            Invocation.method(#getEnforcementSummary, []),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.method(#getEnforcementSummary, []),
            ),
          )
          as String);

  @override
  List<String> getTopViolations() =>
      (super.noSuchMethod(
            Invocation.method(#getTopViolations, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<Map<String, dynamic>> getPeakHours() =>
      (super.noSuchMethod(
            Invocation.method(#getPeakHours, []),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);
}

/// A class which mocks [CityTicketStatsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCityTicketStatsService extends _i1.Mock
    implements _i2.CityTicketStatsService {
  MockCityTicketStatsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CityTicketStats lookup({
    required String? cityId,
    required DateTime? when,
    required double? latitude,
    required double? longitude,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#lookup, [], {
              #cityId: cityId,
              #when: when,
              #latitude: latitude,
              #longitude: longitude,
            }),
            returnValue: _FakeCityTicketStats_0(
              this,
              Invocation.method(#lookup, [], {
                #cityId: cityId,
                #when: when,
                #latitude: latitude,
                #longitude: longitude,
              }),
            ),
          )
          as _i2.CityTicketStats);
}

/// A class which mocks [UserProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProvider extends _i1.Mock implements _i6.UserProvider {
  MockUserProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get firebaseEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#firebaseEnabled),
            returnValue: false,
          )
          as bool);

  @override
  bool get isInitializing =>
      (super.noSuchMethod(
            Invocation.getter(#isInitializing),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(Invocation.getter(#isLoggedIn), returnValue: false)
          as bool);

  @override
  bool get isGuest =>
      (super.noSuchMethod(Invocation.getter(#isGuest), returnValue: false)
          as bool);

  @override
  bool get isOwner =>
      (super.noSuchMethod(Invocation.getter(#isOwner), returnValue: false)
          as bool);

  @override
  List<_i18.Permit> get permits =>
      (super.noSuchMethod(
            Invocation.getter(#permits),
            returnValue: <_i18.Permit>[],
          )
          as List<_i18.Permit>);

  @override
  List<_i19.Reservation> get reservations =>
      (super.noSuchMethod(
            Invocation.getter(#reservations),
            returnValue: <_i19.Reservation>[],
          )
          as List<_i19.Reservation>);

  @override
  List<_i10.StreetSweepingSchedule> get sweepingSchedules =>
      (super.noSuchMethod(
            Invocation.getter(#sweepingSchedules),
            returnValue: <_i10.StreetSweepingSchedule>[],
          )
          as List<_i10.StreetSweepingSchedule>);

  @override
  List<_i20.Ticket> get tickets =>
      (super.noSuchMethod(
            Invocation.getter(#tickets),
            returnValue: <_i20.Ticket>[],
          )
          as List<_i20.Ticket>);

  @override
  List<_i21.SightingReport> get sightings =>
      (super.noSuchMethod(
            Invocation.getter(#sightings),
            returnValue: <_i21.SightingReport>[],
          )
          as List<_i21.SightingReport>);

  @override
  List<_i8.PaymentReceipt> get receipts =>
      (super.noSuchMethod(
            Invocation.getter(#receipts),
            returnValue: <_i8.PaymentReceipt>[],
          )
          as List<_i8.PaymentReceipt>);

  @override
  _i3.AdPreferences get adPreferences =>
      (super.noSuchMethod(
            Invocation.getter(#adPreferences),
            returnValue: _FakeAdPreferences_1(
              this,
              Invocation.getter(#adPreferences),
            ),
          )
          as _i3.AdPreferences);

  @override
  _i4.SubscriptionTier get tier =>
      (super.noSuchMethod(
            Invocation.getter(#tier),
            returnValue: _i4.SubscriptionTier.free,
          )
          as _i4.SubscriptionTier);

  @override
  _i4.SubscriptionPlan get subscriptionPlan =>
      (super.noSuchMethod(
            Invocation.getter(#subscriptionPlan),
            returnValue: _FakeSubscriptionPlan_2(
              this,
              Invocation.getter(#subscriptionPlan),
            ),
          )
          as _i4.SubscriptionPlan);

  @override
  double get maxAlertRadiusMiles =>
      (super.noSuchMethod(
            Invocation.getter(#maxAlertRadiusMiles),
            returnValue: 0.0,
          )
          as double);

  @override
  int get maxAlertsPerDay =>
      (super.noSuchMethod(Invocation.getter(#maxAlertsPerDay), returnValue: 0)
          as int);

  @override
  bool get prioritySupport =>
      (super.noSuchMethod(
            Invocation.getter(#prioritySupport),
            returnValue: false,
          )
          as bool);

  @override
  List<_i9.MaintenanceReport> get maintenanceReports =>
      (super.noSuchMethod(
            Invocation.getter(#maintenanceReports),
            returnValue: <_i9.MaintenanceReport>[],
          )
          as List<_i9.MaintenanceReport>);

  @override
  List<_i22.GarbageSchedule> get garbageSchedules =>
      (super.noSuchMethod(
            Invocation.getter(#garbageSchedules),
            returnValue: <_i22.GarbageSchedule>[],
          )
          as List<_i22.GarbageSchedule>);

  @override
  _i5.CityRulePack get rulePack =>
      (super.noSuchMethod(
            Invocation.getter(#rulePack),
            returnValue: _FakeCityRulePack_3(
              this,
              Invocation.getter(#rulePack),
            ),
          )
          as _i5.CityRulePack);

  @override
  String get cityId =>
      (super.noSuchMethod(
            Invocation.getter(#cityId),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#cityId),
            ),
          )
          as String);

  @override
  String get tenantId =>
      (super.noSuchMethod(
            Invocation.getter(#tenantId),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#tenantId),
            ),
          )
          as String);

  @override
  String get languageCode =>
      (super.noSuchMethod(
            Invocation.getter(#languageCode),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#languageCode),
            ),
          )
          as String);

  @override
  int get towRiskIndex =>
      (super.noSuchMethod(Invocation.getter(#towRiskIndex), returnValue: 0)
          as int);

  @override
  List<String> get cityParkingSuggestions =>
      (super.noSuchMethod(
            Invocation.getter(#cityParkingSuggestions),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  bool get isEmailVerified =>
      (super.noSuchMethod(
            Invocation.getter(#isEmailVerified),
            returnValue: false,
          )
          as bool);

  @override
  int get maxVehicles =>
      (super.noSuchMethod(Invocation.getter(#maxVehicles), returnValue: 0)
          as int);

  @override
  bool get canAddVehicle =>
      (super.noSuchMethod(Invocation.getter(#canAddVehicle), returnValue: false)
          as bool);

  @override
  bool get hasValidNightParkingPermit =>
      (super.noSuchMethod(
            Invocation.getter(#hasValidNightParkingPermit),
            returnValue: false,
          )
          as bool);

  @override
  bool get isNightParkingEnforcementActive =>
      (super.noSuchMethod(
            Invocation.getter(#isNightParkingEnforcementActive),
            returnValue: false,
          )
          as bool);

  @override
  String get nightParkingStatusMessage =>
      (super.noSuchMethod(
            Invocation.getter(#nightParkingStatusMessage),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#nightParkingStatusMessage),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i12.Future<bool> canReceiveAlert() =>
      (super.noSuchMethod(
            Invocation.method(#canReceiveAlert, []),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<void> recordAlertReceived() =>
      (super.noSuchMethod(
            Invocation.method(#recordAlertReceived, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void muteAlerts(Duration? duration) => super.noSuchMethod(
    Invocation.method(#muteAlerts, [duration]),
    returnValueForMissingStub: null,
  );

  @override
  void unmuteAlerts() => super.noSuchMethod(
    Invocation.method(#unmuteAlerts, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> continueAsGuest() =>
      (super.noSuchMethod(
            Invocation.method(#continueAsGuest, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<String?> register({
    required String? name,
    required String? email,
    required String? password,
    String? phone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #name: name,
              #email: email,
              #password: password,
              #phone: phone,
            }),
            returnValue: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);

  @override
  _i12.Future<String?> resendVerificationEmail() =>
      (super.noSuchMethod(
            Invocation.method(#resendVerificationEmail, []),
            returnValue: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);

  @override
  _i12.Future<void> refreshUserData() =>
      (super.noSuchMethod(
            Invocation.method(#refreshUserData, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<String?> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);

  @override
  _i12.Future<String?> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);

  @override
  _i12.Future<_i6.PhoneAuthStartResult> startPhoneSignIn(String? phoneNumber) =>
      (super.noSuchMethod(
            Invocation.method(#startPhoneSignIn, [phoneNumber]),
            returnValue: _i12.Future<_i6.PhoneAuthStartResult>.value(
              _FakePhoneAuthStartResult_4(
                this,
                Invocation.method(#startPhoneSignIn, [phoneNumber]),
              ),
            ),
          )
          as _i12.Future<_i6.PhoneAuthStartResult>);

  @override
  _i12.Future<String?> confirmPhoneCode({
    required String? verificationId,
    required String? smsCode,
    String? phoneNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#confirmPhoneCode, [], {
              #verificationId: verificationId,
              #smsCode: smsCode,
              #phoneNumber: phoneNumber,
            }),
            returnValue: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);

  @override
  _i12.Future<String?> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);

  @override
  _i12.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<String?> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);

  @override
  _i12.Future<void> updateProfile({
    String? name,
    String? email,
    String? phone,
    String? address,
    String? formattedAddress,
    double? addressLatitude,
    double? addressLongitude,
    _i3.AdPreferences? adPreferences,
    _i4.SubscriptionTier? tier,
    String? cityId,
    String? tenantId,
    String? languageCode,
    _i5.CityRulePack? rulePack,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #name: name,
              #email: email,
              #phone: phone,
              #address: address,
              #formattedAddress: formattedAddress,
              #addressLatitude: addressLatitude,
              #addressLongitude: addressLongitude,
              #adPreferences: adPreferences,
              #tier: tier,
              #cityId: cityId,
              #tenantId: tenantId,
              #languageCode: languageCode,
              #rulePack: rulePack,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> setGarbageSchedules(
    List<_i22.GarbageSchedule>? schedules,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setGarbageSchedules, [schedules]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<({String? message, int usersWarned})> reportSighting({
    required _i21.SightingType? type,
    required String? location,
    String? notes = '',
    double? latitude,
    double? longitude,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reportSighting, [], {
              #type: type,
              #location: location,
              #notes: notes,
              #latitude: latitude,
              #longitude: longitude,
            }),
            returnValue:
                _i12.Future<({String? message, int usersWarned})>.value((
                  message: null,
                  usersWarned: 0,
                )),
          )
          as _i12.Future<({String? message, int usersWarned})>);

  @override
  _i12.Future<void> deleteSighting(String? sightingId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSighting, [sightingId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> cleanupOldSightings({int? days = 7}) =>
      (super.noSuchMethod(
            Invocation.method(#cleanupOldSightings, [], {#days: days}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i7.PermitEligibilityResult evaluatePermitEligibility({
    required _i18.PermitType? type,
    required bool? hasProofOfResidence,
    required int? unpaidTicketCount,
    required bool? isLowIncome,
    required bool? isSenior,
    required bool? ecoVehicle,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#evaluatePermitEligibility, [], {
              #type: type,
              #hasProofOfResidence: hasProofOfResidence,
              #unpaidTicketCount: unpaidTicketCount,
              #isLowIncome: isLowIncome,
              #isSenior: isSenior,
              #ecoVehicle: ecoVehicle,
            }),
            returnValue: _FakePermitEligibilityResult_5(
              this,
              Invocation.method(#evaluatePermitEligibility, [], {
                #type: type,
                #hasProofOfResidence: hasProofOfResidence,
                #unpaidTicketCount: unpaidTicketCount,
                #isLowIncome: isLowIncome,
                #isSenior: isSenior,
                #ecoVehicle: ecoVehicle,
              }),
            ),
          )
          as _i7.PermitEligibilityResult);

  @override
  _i8.PaymentReceipt settlePermit({
    required _i7.PermitEligibilityResult? result,
    required String? method,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#settlePermit, [], {
              #result: result,
              #method: method,
            }),
            returnValue: _FakePaymentReceipt_6(
              this,
              Invocation.method(#settlePermit, [], {
                #result: result,
                #method: method,
              }),
            ),
          )
          as _i8.PaymentReceipt);

  @override
  _i12.Future<void> updateAdPreferences(_i3.AdPreferences? prefs) =>
      (super.noSuchMethod(
            Invocation.method(#updateAdPreferences, [prefs]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updateSubscriptionTier(_i4.SubscriptionTier? tier) =>
      (super.noSuchMethod(
            Invocation.method(#updateSubscriptionTier, [tier]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> grantAdRewardTrial({int? days = 3}) =>
      (super.noSuchMethod(
            Invocation.method(#grantAdRewardTrial, [], {#days: days}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updateCityAndTenant({
    required String? cityId,
    required String? tenantId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateCityAndTenant, [], {
              #cityId: cityId,
              #tenantId: tenantId,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updateLanguage(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#updateLanguage, [languageCode]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i20.Ticket? findTicket(String? plate, String? ticketId) =>
      (super.noSuchMethod(Invocation.method(#findTicket, [plate, ticketId]))
          as _i20.Ticket?);

  @override
  void addTicket(_i20.Ticket? ticket) => super.noSuchMethod(
    Invocation.method(#addTicket, [ticket]),
    returnValueForMissingStub: null,
  );

  @override
  void deleteTicket(String? ticketId) => super.noSuchMethod(
    Invocation.method(#deleteTicket, [ticketId]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.PaymentReceipt settleTicket({
    required _i20.Ticket? ticket,
    required String? method,
    required bool? lowIncome,
    required bool? firstOffense,
    required bool? resident,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#settleTicket, [], {
              #ticket: ticket,
              #method: method,
              #lowIncome: lowIncome,
              #firstOffense: firstOffense,
              #resident: resident,
            }),
            returnValue: _FakePaymentReceipt_6(
              this,
              Invocation.method(#settleTicket, [], {
                #ticket: ticket,
                #method: method,
                #lowIncome: lowIncome,
                #firstOffense: firstOffense,
                #resident: resident,
              }),
            ),
          )
          as _i8.PaymentReceipt);

  @override
  _i12.Future<void> syncTicketsWithBackend() =>
      (super.noSuchMethod(
            Invocation.method(#syncTicketsWithBackend, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i9.MaintenanceReport> submitMaintenanceReport({
    required _i9.MaintenanceCategory? category,
    required String? description,
    required String? location,
    double? latitude,
    double? longitude,
    String? photoPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitMaintenanceReport, [], {
              #category: category,
              #description: description,
              #location: location,
              #latitude: latitude,
              #longitude: longitude,
              #photoPath: photoPath,
            }),
            returnValue: _i12.Future<_i9.MaintenanceReport>.value(
              _FakeMaintenanceReport_7(
                this,
                Invocation.method(#submitMaintenanceReport, [], {
                  #category: category,
                  #description: description,
                  #location: location,
                  #latitude: latitude,
                  #longitude: longitude,
                  #photoPath: photoPath,
                }),
              ),
            ),
          )
          as _i12.Future<_i9.MaintenanceReport>);

  @override
  _i12.Future<void> scheduleGarbageReminders({
    Duration? nightBefore = const Duration(hours: 12),
    Duration? morningOf = const Duration(hours: 2),
    String? languageCode = 'en',
    bool? useRepeatingReminders = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleGarbageReminders, [], {
              #nightBefore: nightBefore,
              #morningOf: morningOf,
              #languageCode: languageCode,
              #useRepeatingReminders: useRepeatingReminders,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  bool hasFeature(_i4.PremiumFeature? feature) =>
      (super.noSuchMethod(
            Invocation.method(#hasFeature, [feature]),
            returnValue: false,
          )
          as bool);

  @override
  _i12.Future<String?> changePassword(String? password) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [password]),
            returnValue: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);

  @override
  _i12.Future<bool> addVehicle(_i23.Vehicle? vehicle) =>
      (super.noSuchMethod(
            Invocation.method(#addVehicle, [vehicle]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<void> updateVehicle(_i23.Vehicle? vehicle) =>
      (super.noSuchMethod(
            Invocation.method(#updateVehicle, [vehicle]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> removeVehicle(String? vehicleId) =>
      (super.noSuchMethod(
            Invocation.method(#removeVehicle, [vehicleId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updatePreferences({
    bool? parkingNotifications,
    bool? towAlerts,
    bool? reminderNotifications,
    String? defaultVehicleId,
    int? geoRadiusMiles,
    bool? ticketRiskAlerts,
    bool? ticketDueDateReminders,
    bool? aspMorningReminder,
    bool? aspEveningWarning,
    bool? aspMidnightAlert,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePreferences, [], {
              #parkingNotifications: parkingNotifications,
              #towAlerts: towAlerts,
              #reminderNotifications: reminderNotifications,
              #defaultVehicleId: defaultVehicleId,
              #geoRadiusMiles: geoRadiusMiles,
              #ticketRiskAlerts: ticketRiskAlerts,
              #ticketDueDateReminders: ticketDueDateReminders,
              #aspMorningReminder: aspMorningReminder,
              #aspEveningWarning: aspEveningWarning,
              #aspMidnightAlert: aspMidnightAlert,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> addPermit(_i18.Permit? permit) =>
      (super.noSuchMethod(
            Invocation.method(#addPermit, [permit]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> renewPermit(String? permitId) =>
      (super.noSuchMethod(
            Invocation.method(#renewPermit, [permitId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updatePermitStatus(
    String? permitId,
    _i18.PermitStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePermitStatus, [permitId, status]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> toggleOfflineAccess(String? permitId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleOfflineAccess, [permitId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updatePermitVehicles(
    String? permitId,
    List<String>? vehicleIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePermitVehicles, [permitId, vehicleIds]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updateAutoRenew(String? permitId, bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#updateAutoRenew, [permitId, enabled]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> createReservation(_i19.Reservation? reservation) =>
      (super.noSuchMethod(
            Invocation.method(#createReservation, [reservation]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updateReservationStatus(
    String? reservationId,
    _i19.ReservationStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateReservationStatus, [
              reservationId,
              status,
            ]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> recordPayment({
    required String? reservationId,
    required String? paymentMethod,
    required double? amount,
    required String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordPayment, [], {
              #reservationId: reservationId,
              #paymentMethod: paymentMethod,
              #amount: amount,
              #transactionId: transactionId,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updateSweepingNotifications(
    String? id, {
    bool? gpsMonitoring,
    bool? advance24h,
    bool? final2h,
    int? customMinutes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateSweepingNotifications,
              [id],
              {
                #gpsMonitoring: gpsMonitoring,
                #advance24h: advance24h,
                #final2h: final2h,
                #customMinutes: customMinutes,
              },
            ),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<String?> fetchRouteForLocation({
    required double? lat,
    required double? lng,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRouteForLocation, [], {
              #lat: lat,
              #lng: lng,
            }),
            returnValue: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);

  @override
  _i12.Future<_i10.StreetSweepingSchedule> addSweepingScheduleFromUserEntry({
    required String? broomCode,
    required int? sweepDay,
    required List<int>? weekPattern,
    String? side = 'Both sides',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addSweepingScheduleFromUserEntry, [], {
              #broomCode: broomCode,
              #sweepDay: sweepDay,
              #weekPattern: weekPattern,
              #side: side,
            }),
            returnValue: _i12.Future<_i10.StreetSweepingSchedule>.value(
              _FakeStreetSweepingSchedule_8(
                this,
                Invocation.method(#addSweepingScheduleFromUserEntry, [], {
                  #broomCode: broomCode,
                  #sweepDay: sweepDay,
                  #weekPattern: weekPattern,
                  #side: side,
                }),
              ),
            ),
          )
          as _i12.Future<_i10.StreetSweepingSchedule>);

  @override
  _i12.Future<void> refreshSweepingSchedules() =>
      (super.noSuchMethod(
            Invocation.method(#refreshSweepingSchedules, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> logVehicleMoved(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#logVehicleMoved, [id]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i24.NightParkingZoneResult?> checkNightParkingForAddress() =>
      (super.noSuchMethod(
            Invocation.method(#checkNightParkingForAddress, []),
            returnValue: _i12.Future<_i24.NightParkingZoneResult?>.value(),
          )
          as _i12.Future<_i24.NightParkingZoneResult?>);

  @override
  _i12.Future<void> setNightParkingPermission({
    required String? licensePlate,
    String? vehicleDescription,
    _i24.NightParkingStatus? status = _i24.NightParkingStatus.pending,
    DateTime? expirationDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setNightParkingPermission, [], {
              #licensePlate: licensePlate,
              #vehicleDescription: vehicleDescription,
              #status: status,
              #expirationDate: expirationDate,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> activateNightParkingPermission({
    required DateTime? expirationDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#activateNightParkingPermission, [], {
              #expirationDate: expirationDate,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> setNightParkingReminders(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setNightParkingReminders, [enabled]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> clearNightParkingPermission() =>
      (super.noSuchMethod(
            Invocation.method(#clearNightParkingPermission, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void addListener(_i25.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i25.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
